name: flutter_tutorial
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^2.1.0
  marquee: ^2.1.0
  widget_with_codeview: ^1.0.5
  video_player:
  url_launcher: ^5.4.0
  youtube_player_flutter: ^7.0.0+7
  expandable_text: ^2.2.0
  curved_navigation_bar: ^0.3.7
  animated_splash_screen: ^1.1.0
  animated_text_kit: ^4.2.1
  fluttertoast: ^8.0.7
  like_button: ^2.0.2  
  flutter_colorpicker: ^0.4.0
  provider: ^5.0.0
  shared_preferences: ^2.0.6
  pattern_formatter: ^2.0.0
  http: ^0.12.0+2
  random_pk: ^0.0.3 
#  Flutter package that gives a container with random color.
#  cupertino_icons: ^1.0.0choco
#  font_awesome_flutter: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/localJson/
    - assets/
    - assets/images/ListView/
    - assets/images/
    - lib/Text/
    - lib/AlertDialog/
    - lib/Align/
    - lib/Others/Assignments/
    - lib/Bar/AppBar/
    - lib/Bar/BottomNavigationBar/
    - lib/Bar/Navigationbar/
    - lib/Bar/Snackbar/
    - lib/Box/Box_DecoratedBox/
    - lib/Box/Box_FittedBox/
    - lib/Box/Box_RotatedBox/
    - lib/Box/Box_SizedBox/
    - lib/Buttons/ElevatedButton/
    - lib/Buttons/FlatButton/
    - lib/Buttons/FloatingActionButton/
    - lib/Buttons/RadioButton/
    - lib/Buttons/IconicButtons/
    - lib/Card/
    - lib/Comments/
    - lib/Container/
    - lib/CustomWidgets/
    - lib/DART/
    - lib/Divider/Que02.dart
    - lib/Drawer/
    - lib/Others/General/
    - lib/Others/Theme/
    - lib/Others/Future/
    - lib/Others/GesterDetector/
    - lib/GridView/
    - lib/GridView/StaggeredGridView/
    - lib/Icons/
    - lib/Image/
    - lib/Image/Clipping/
    - lib/Others/InkWell/
    - lib/Others/Interface/
    - lib/ListView/
    - lib/Others/Material/
    - lib/models/
    - lib/Others/Opacity/
    - lib/Padding/
    - lib/Others/Placeholder/
    - lib/Others/Positioned/
    - lib/Others/ProgressIndicator_Loading/
    - lib/Row/
    - lib/Slider/
    - lib/Dropdown/
    - lib/Others/Spacer/
    - lib/Others/Stack_IndexStack_Positioned/
    - lib/Switch/
    - lib/SetUpAPK/
    - lib/Tab/
    - lib/API/
    - lib/API/SimpleMethod/
    - lib/API/models/Assignment1/
    - lib/API/models/Assignment2/
    - lib/API/models/Assignment3/
    - lib/API/models/Assignment4/
    - lib/API/models/Assignment5/
    - lib/API/models/Assignment6/
    - lib/API/models/Assignment7/
    - lib/API/models/Assignment8/
    - lib/API/models/Assignment9/
    - lib/API/models/Assignment10/
    - lib/API/models/Assignment11/
    - lib/TextField/
    - lib/TextFormField/
    - lib/Transform/
    - lib/Others/Visibility/
    - assets/help/AlertDialog/ 
    - assets/help/Align/ 
    - assets/help/Others/Assignments/ 
    - assets/help/Bar/AppBar/ 
    - assets/help/Bar/Snackbar/ 
    - assets/help/Box/
    - assets/help/Box/Box_DecoratedBox/
    - assets/help/Box/Box_FittedBox/
    - assets/help/Box/Box_FractionallySizedBox/
    - assets/help/Box/Box_SizedBox/
    - assets/help/Buttons/ElevatedButton/
    - assets/help/Buttons/FlatButton/
    - assets/help/Buttons/FloatingActionButton/
    - assets/help/Buttons/RadioButton/
    - assets/help/Buttons/IconicButtons/
    - assets/help/Card/
    - assets/help/Comments/
    - assets/help/Container/
    - assets/help/Others/CustomWidgets/
    - assets/help/Dart/
    - assets/help/Divider/
    - assets/help/Drawer/
    - assets/help/Box/Box_FractionallySizedBox/
    - assets/help/Others/GesterDetector/
    - assets/help/Others/GridView/
    - assets/help/Icon/
    - assets/help/Image/
    - assets/help/Others/InkWell/
    - assets/help/Others/Material/
    - assets/help/Others/Opacity/
    - assets/help/Others/Placeholder/
    - assets/help/Others/ProgressIndicator_Loading/
    - assets/help/Others/Spacer/
    - assets/help/Others/Stack_IndexStack_Positioned/
    - assets/help/Others/Visibility/
    - assets/help/Others/General/
    - assets/help/Padding/
    - assets/help/ListView/
    - assets/help/Properties/
    - assets/help/Row/
    - assets/help/Slider/
    - assets/help/Switch/
    - assets/help/SetUpAPK/
    - assets/help/Tab/
    - assets/help/Text/
    - assets/help/TextField/
    - assets/help/Transform/
    - assets/help/API/

   



  #  - assets/images/loading.gif
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
